/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ConversationMessageSortEnum = 'MESSAGE_TYPE' | 'MESSAGE_TOPIC' | 'CONTENT' | 'DATE';

export const ConversationMessageSortEnum = {
    MessageType: 'MESSAGE_TYPE' as ConversationMessageSortEnum,
    MessageTopic: 'MESSAGE_TOPIC' as ConversationMessageSortEnum,
    Content: 'CONTENT' as ConversationMessageSortEnum,
    Date: 'DATE' as ConversationMessageSortEnum
};

