/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConversationMessage } from './conversation-message';
import { MessageTopic } from './message-topic';
import { MessageType } from './message-type';
import { GenerationType } from './generation-type';


export interface Conversation { 
    id?: string;
    generationId?: string;
    conversationType?: GenerationType;
    messageType?: MessageType;
    messageTopic?: MessageTopic;
    maxInteractionNumber?: number;
    minInteractionNumber?: number;
    messages?: Array<ConversationMessage>;
}
export namespace Conversation {
}


