/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type InstantMessageSortEnum = 'MESSAGE_TYPE' | 'MESSAGE_TOPIC' | 'CONTENT' | 'DATE';

export const InstantMessageSortEnum = {
    MessageType: 'MESSAGE_TYPE' as InstantMessageSortEnum,
    MessageTopic: 'MESSAGE_TOPIC' as InstantMessageSortEnum,
    Content: 'CONTENT' as InstantMessageSortEnum,
    Date: 'DATE' as InstantMessageSortEnum
};

