/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageTopic } from './message-topic';
import { MessageType } from './message-type';


export interface InstantMessage { 
    id?: string;
    messageType?: MessageType;
    messageTopic?: MessageTopic;
    content?: string;
    generationId?: string;
    generationBusinessId?: string;
}
export namespace InstantMessage {
}


