/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterlocutorType } from './interlocutor-type';


export interface Interlocutor { 
    id?: number;
    interlocutorType?: InterlocutorType;
}
export namespace Interlocutor {
}


