/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MessageTopic = 'WORK' | 'SPORT' | 'POLITICS' | 'SCIENCE' | 'TECHNOLOGY' | 'ART' | 'MUSIC' | 'MOVIES' | 'GAMES' | 'LITERATURE' | 'PHILOSOPHY' | 'RELIGION' | 'HISTORY' | 'GEOGRAPHY' | 'ECONOMY' | 'SOCIETY' | 'HEALTH' | 'EDUCATION' | 'ENVIRONMENT' | 'ROMANCE' | 'OTHER';

export const MessageTopic = {
    Work: 'WORK' as MessageTopic,
    Sport: 'SPORT' as MessageTopic,
    Politics: 'POLITICS' as MessageTopic,
    Science: 'SCIENCE' as MessageTopic,
    Technology: 'TECHNOLOGY' as MessageTopic,
    Art: 'ART' as MessageTopic,
    Music: 'MUSIC' as MessageTopic,
    Movies: 'MOVIES' as MessageTopic,
    Games: 'GAMES' as MessageTopic,
    Literature: 'LITERATURE' as MessageTopic,
    Philosophy: 'PHILOSOPHY' as MessageTopic,
    Religion: 'RELIGION' as MessageTopic,
    History: 'HISTORY' as MessageTopic,
    Geography: 'GEOGRAPHY' as MessageTopic,
    Economy: 'ECONOMY' as MessageTopic,
    Society: 'SOCIETY' as MessageTopic,
    Health: 'HEALTH' as MessageTopic,
    Education: 'EDUCATION' as MessageTopic,
    Environment: 'ENVIRONMENT' as MessageTopic,
    Romance: 'ROMANCE' as MessageTopic,
    Other: 'OTHER' as MessageTopic
};

