/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { InstantMessage } from '../model/models';
import { InstantMessageBatchCreation } from '../model/models';
import { InstantMessagesPage } from '../model/models';
import { PagedInstantMessageQuery } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InstantMessageServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Generate instant messages
     * Generate a instant messages
     * @param instantMessageBatchCreation 
     */
    createMessage(instantMessageBatchCreation: InstantMessageBatchCreation, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete a instant instant message
     * Delete a instant instant message
     * @param instantMessageId 
     */
    deleteInstantMessageById(instantMessageId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Find instant message list by generation id
     * Find instant message list by generation id
     * @param generationId 
     */
    findInstantMessagesByGenerationId(generationId: string, extraHttpRequestParams?: any): Observable<Array<InstantMessage>>;

    /**
     * Get a instant instant message
     * Get a instant instant message
     * @param instantMessageId 
     */
    getInstantMessageById(instantMessageId: string, extraHttpRequestParams?: any): Observable<InstantMessage>;

    /**
     * Search instant messages with pagination
     * Search instant messages with pagination
     * @param pagedInstantMessageQuery 
     */
    searchInstantMessagesPaginate(pagedInstantMessageQuery?: PagedInstantMessageQuery, extraHttpRequestParams?: any): Observable<InstantMessagesPage>;

}
