/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BusinessErrorCode } from './business-error-code';


/**
 * Only applicable when {errorType} is Business
 */
export interface BusinessError { 
    code?: BusinessErrorCode;
}
export namespace BusinessError {
}


