/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GenerationType = 'INSTANT_MESSAGE' | 'CONVERSATION';

export const GenerationType = {
    InstantMessage: 'INSTANT_MESSAGE' as GenerationType,
    Conversation: 'CONVERSATION' as GenerationType
};

