/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageTopic } from './message-topic';
import { MessageType } from './message-type';


export interface GenerationCreation { 
    topic: MessageTopic;
    type: MessageType;
    quantity: number;
    systemPrompt?: string;
    userPrompt?: string;
}
export namespace GenerationCreation {
}


