/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type InterlocutorType = 'GENUINE' | 'TROLL' | 'SOCIAL_ENGINEER' | 'null';

export const InterlocutorType = {
    Genuine: 'GENUINE' as InterlocutorType,
    Troll: 'TROLL' as InterlocutorType,
    SocialEngineer: 'SOCIAL_ENGINEER' as InterlocutorType,
    Null: 'null' as InterlocutorType
};

