/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortDirection } from './sort-direction';
import { AuthorSortEnum } from './author-sort-enum';
import { QueryPage } from './query-page';
import { AuthorQuery } from './author-query';


export interface PagedAuthorQuery { 
    page: QueryPage;
    query: AuthorQuery;
    sortField?: AuthorSortEnum;
    sortDirection?: SortDirection;
}
export namespace PagedAuthorQuery {
}


