/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectType } from './project-type';


export interface ProjectCreation { 
    projectType: ProjectType;
    name: string;
    description: string;
    organization?: string;
    authorId: string;
}
export namespace ProjectCreation {
}


