/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProjectSortEnum = 'NAME' | 'ORGANIZATION' | 'AUTHOR_TRIGRAM';

export const ProjectSortEnum = {
    Name: 'NAME' as ProjectSortEnum,
    Organization: 'ORGANIZATION' as ProjectSortEnum,
    AuthorTrigram: 'AUTHOR_TRIGRAM' as ProjectSortEnum
};

