/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FakeRealRatios } from './fake-real-ratios';
import { TypeRatios } from './type-ratios';
import { MessageTypeTopicRatios } from './message-type-topic-ratios';


export interface Statistic { 
    id: string;
    fakeRealRatios: FakeRealRatios;
    typeRatios: TypeRatios;
    genuineTopicRatios?: MessageTypeTopicRatios;
    socialEngineeringTopicRatios?: MessageTypeTopicRatios;
    trollingTopicRatios?: MessageTypeTopicRatios;
}

