/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type BusinessErrorCode = 'A' | 'B' | 'C';

export const BusinessErrorCode = {
    A: 'A' as BusinessErrorCode,
    B: 'B' as BusinessErrorCode,
    C: 'C' as BusinessErrorCode
};

