/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Interlocutor } from './interlocutor';


export interface ConversationMessage { 
    id?: string;
    conversationId?: string;
    content?: string;
    sender?: Interlocutor;
    receiver?: Interlocutor;
}

