/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorType } from './error-type';
import { BusinessError } from './business-error';


export interface ErrorResponse { 
    errorType?: ErrorType;
    /**
     * A GUID identifying univoquely the error instance in the applicative log system
     */
    technicalErrorInstanceId?: string;
    /**
     * A GUID identifying a request
     */
    correlationId?: string | null;
    businessError?: BusinessError | null;
    message?: string;
}
export namespace ErrorResponse {
}


