/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortDirection } from './sort-direction';
import { GenerationSortEnum } from './generation-sort-enum';
import { QueryPage } from './query-page';
import { GenerationQuery } from './generation-query';


export interface PagedGenerationQuery { 
    page: QueryPage;
    query: GenerationQuery;
    sortField?: GenerationSortEnum;
    sortDirection?: SortDirection;
}
export namespace PagedGenerationQuery {
}


