/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Dataset } from './dataset';
import { ProjectType } from './project-type';
import { Author } from './author';


export interface Project { 
    id?: string;
    creationDate?: string;
    modificationDate?: string;
    type?: ProjectType;
    name?: string;
    description?: string;
    organization?: string;
    author?: Author;
    datasets?: Array<Dataset>;
}
export namespace Project {
}


