/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Author } from '../model/models';
import { AuthorCreation } from '../model/models';
import { AuthorsPage } from '../model/models';
import { ErrorResponse } from '../model/models';
import { PagedAuthorQuery } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthorServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create author
     * Create author
     * @param authorCreation 
     */
    createAuthor(authorCreation: AuthorCreation, extraHttpRequestParams?: any): Observable<Author>;

    /**
     * Get a author by id
     * Get a author by id
     * @param authorId 
     */
    getAuthorById(authorId: string, extraHttpRequestParams?: any): Observable<Author>;

    /**
     * Get authors
     * Get authors
     */
    getAuthorList(extraHttpRequestParams?: any): Observable<Array<Author>>;

    /**
     * Search authors with pagination
     * Search authors with pagination
     * @param pagedAuthorQuery 
     */
    searchAuthorsPaginate(pagedAuthorQuery?: PagedAuthorQuery, extraHttpRequestParams?: any): Observable<AuthorsPage>;

}
