/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthorQuery { 
    lastname?: string;
    firstname?: string;
    organization?: string;
    authorFunction?: string;
    trigram?: string;
    email?: string;
}

