/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AuthorSortEnum = 'LASTNAME' | 'FIRSTNAME' | 'AUTHOR_TRIGRAM';

export const AuthorSortEnum = {
    Lastname: 'LASTNAME' as AuthorSortEnum,
    Firstname: 'FIRSTNAME' as AuthorSortEnum,
    AuthorTrigram: 'AUTHOR_TRIGRAM' as AuthorSortEnum
};

