export * from './author.service';
import { AuthorService } from './author.service';
export * from './author.serviceInterface';
export * from './conversation.service';
import { ConversationService } from './conversation.service';
export * from './conversation.serviceInterface';
export * from './conversation-message.service';
import { ConversationMessageService } from './conversation-message.service';
export * from './conversation-message.serviceInterface';
export * from './dataset.service';
import { DatasetService } from './dataset.service';
export * from './dataset.serviceInterface';
export * from './generation.service';
import { GenerationService } from './generation.service';
export * from './generation.serviceInterface';
export * from './instant-message.service';
import { InstantMessageService } from './instant-message.service';
export * from './instant-message.serviceInterface';
export * from './ongoing-generation.service';
import { OngoingGenerationService } from './ongoing-generation.service';
export * from './ongoing-generation.serviceInterface';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './project.serviceInterface';
export * from './statistic.service';
import { StatisticService } from './statistic.service';
export * from './statistic.serviceInterface';
export const APIS = [AuthorService, ConversationService, ConversationMessageService, DatasetService, GenerationService, InstantMessageService, OngoingGenerationService, ProjectService, StatisticService];
