/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { OngoingGeneration } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OngoingGenerationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get an ongoing generation by id
     * Get an ongoing generation by id
     * @param ongoingGenerationId 
     */
    getOngoingGenerationById(ongoingGenerationId: string, extraHttpRequestParams?: any): Observable<OngoingGeneration>;

}
