/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { PagedProjectQuery } from '../model/models';
import { Project } from '../model/models';
import { ProjectCreation } from '../model/models';
import { ProjectType } from '../model/models';
import { ProjectsPage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProjectServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create project
     * Create project
     * @param projectCreation 
     */
    createProject(projectCreation: ProjectCreation, extraHttpRequestParams?: any): Observable<Project>;

    /**
     * Delete project
     * Delete project
     * @param projectId 
     */
    deleteProject(projectId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get a project by id
     * Get a project by id
     * @param projectId 
     */
    getProjectById(projectId: string, extraHttpRequestParams?: any): Observable<Project>;

    /**
     * Search projects with pagination
     * Search projects with pagination
     * @param projectType 
     * @param pagedProjectQuery 
     */
    searchProjectsPaginate(projectType: ProjectType, pagedProjectQuery?: PagedProjectQuery, extraHttpRequestParams?: any): Observable<ProjectsPage>;

    /**
     * Update project data
     * Update project data
     * @param projectId 
     * @param requestBody 
     */
    updateProjectData(projectId: string, requestBody: Array<string>, extraHttpRequestParams?: any): Observable<Project>;

}
