/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { Statistic } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface StatisticServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get a statistic by id
     * Get a statistic by id
     * @param statisticId 
     */
    getStatisticById(statisticId: string, extraHttpRequestParams?: any): Observable<Statistic>;

}
