/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { ConversationSummary } from './conversation-summary';


export interface ConversationsPage { 
    pagination: Pagination;
    conversations: Array<ConversationSummary>;
}

