/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectSortEnum } from './project-sort-enum';
import { SortDirection } from './sort-direction';
import { ProjectQuery } from './project-query';
import { QueryPage } from './query-page';


export interface PagedProjectQuery { 
    page: QueryPage;
    query: ProjectQuery;
    sortField?: ProjectSortEnum;
    sortDirection?: SortDirection;
}
export namespace PagedProjectQuery {
}


