/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectQuery { 
    name?: string;
    description?: string;
    organization?: string;
    authorTrigram?: string;
    startDate?: string;
    endDate?: string;
}

