/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { Generation } from '../model/models';
import { GenerationType } from '../model/models';
import { GenerationsPage } from '../model/models';
import { PagedGenerationQuery } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GenerationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete a generation by id
     * Delete a generation by id
     * @param generationId 
     * @param generationType 
     */
    deleteGenerationById(generationId: string, generationType: GenerationType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get a generation by id
     * Get a generation by id
     * @param generationId 
     */
    getGenerationById(generationId: string, extraHttpRequestParams?: any): Observable<Generation>;

    /**
     * Search generations with pagination
     * Search generations with pagination
     * @param generationType 
     * @param pagedGenerationQuery 
     */
    searchGenerationsPaginate(generationType: GenerationType, pagedGenerationQuery?: PagedGenerationQuery, extraHttpRequestParams?: any): Observable<GenerationsPage>;

}
