openapi: "3.0.0"
info:
  version: 1.1.0
  title: 'FpGen api'
  description: 'API for fake profile dataset generator project'

tags:
  - name: InstantMessage
  - name: Conversation

paths:
  /v1/instantMessages:
    post:
      tags:
        - InstantMessage
      summary: "Generate instant messages"
      description: "Generate a instant messages"
      operationId: createMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstantMessageBatchCreation'

      responses:
        201:
          description: 'Instant messages generation request successfully sent'
        400:
          $ref: 'common.yaml#/components/responses/400'
        403:
          $ref: 'common.yaml#/components/responses/403'
        404:
          $ref: 'common.yaml#/components/responses/404'
        500:
          $ref: 'common.yaml#/components/responses/500'

  /v1/instantMessages/{instantMessageId}:
    get:
      tags:
        - InstantMessage
      summary: "Get a instant instant message"
      description: "Get a instant instant message"
      operationId: getInstantMessageById
      parameters:
        - $ref: '#/components/parameters/instantMessageId'
      responses:
        200:
          description: 'Instant message successfully recovered'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstantMessage'
        400:
          $ref: 'common.yaml#/components/responses/400'
        403:
          $ref: 'common.yaml#/components/responses/403'
        404:
          $ref: 'common.yaml#/components/responses/404'
        500:
          $ref: 'common.yaml#/components/responses/500'

  /v1/conversations:
    post:
      tags:
        - Conversation
      summary: "Generate conversations"
      description: "Generate conversations"
      operationId: generateConversations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversationBatchCreation'

      responses:
        201:
          description: 'Conversations generation request successfully sent'
        400:
          $ref: 'common.yaml#/components/responses/400'
        403:
          $ref: 'common.yaml#/components/responses/403'
        404:
          $ref: 'common.yaml#/components/responses/404'
        500:
          $ref: 'common.yaml#/components/responses/500'

  /v1/conversations/{conversationId}:
    get:
      tags:
        - Conversation
      summary: "Get a conversation by id"
      description: "Get a conversation by id"
      operationId: getConversationById
      parameters:
        - $ref: '#/components/parameters/conversationId'
      responses:
        200:
          description: 'Conversation successfully recovered'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        400:
          $ref: 'common.yaml#/components/responses/400'
        403:
          $ref: 'common.yaml#/components/responses/403'
        404:
          $ref: 'common.yaml#/components/responses/404'
        500:
          $ref: 'common.yaml#/components/responses/500'

  /v1/conversations/{conversationId}/{conversationInstantMessageId}:
    get:
      tags:
        - Conversation
      summary: "Get a conversation by id"
      description: "Get a conversation by id"
      operationId: getConversationInstantMessageById
      parameters:
        - $ref: '#/components/parameters/conversationId'
        - $ref: '#/components/parameters/conversationInstantMessageId'
      responses:
        200:
          description: 'Conversation instant message successfully recovered'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationInstantMessage'
        400:
          $ref: 'common.yaml#/components/responses/400'
        403:
          $ref: 'common.yaml#/components/responses/403'
        404:
          $ref: 'common.yaml#/components/responses/404'
        500:
          $ref: 'common.yaml#/components/responses/500'

# components
components:
  parameters:
    instantMessageId:
      name: instantMessageId
      in: path
      required: true
      schema:
        $ref: 'common.yaml#/components/schemas/UUID'

    conversationId:
      name: conversationId
      in: path
      required: true
      schema:
        $ref: 'common.yaml#/components/schemas/UUID'

    conversationInstantMessageId:
      name: conversationInstantMessageId
      in: path
      required: true
      schema:
        $ref: 'common.yaml#/components/schemas/UUID'

  schemas:
    # bodies
    # request bodies
    InstantMessageCreation:
      type: object
      required:
        - messageType
        - messageTopic
        - quantity
      properties:
        messageType:
          $ref: '#/components/schemas/MessageType'
        messageTopic:
          $ref: '#/components/schemas/MessageTopic'
        quantity:
          type: integer

    InstantMessageBatchCreation:
        type: object
        required:
            - instantMessageCreationList
        properties:
          instantMessageCreationList:
            type: array
            items:
              $ref: '#/components/schemas/InstantMessageCreation'


    ConversationCreation:
      type: object
      required:
        - messageType
        - messageTopic
        - quantity
      properties:
        messageType:
          $ref: '#/components/schemas/MessageType'
        messageTopic:
          $ref: '#/components/schemas/MessageTopic'
        quantity:
          type: integer

    ConversationBatchCreation:
      type: object
      required:
        - conversationCreationList
      properties:
        conversationCreationList:
          type: array
          items:
            $ref: '#/components/schemas/ConversationCreation'

    # response bodies
    InstantMessage:
      type: object
      properties:
        id:
          $ref: 'common.yaml#/components/schemas/UUID'
        messageType:
          $ref: '#/components/schemas/MessageType'
        messageTopic:
          $ref: '#/components/schemas/MessageTopic'
        content:
          type: string
        generation:
          $ref: '#/components/schemas/Generation'

    ConversationInstantMessage:
      type: object
      properties:
        id:
          $ref: 'common.yaml#/components/schemas/UUID'
        content:
          type: string
        sender:
          type: integer
        receiver:
          type: integer

    Conversation:
      type: object
      properties:
        id:
          $ref: 'common.yaml#/components/schemas/UUID'
        generation:
          $ref: '#/components/schemas/Generation'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/ConversationInstantMessage'

    Generation:
      type: object
      properties:
        id:
          $ref: 'common.yaml#/components/schemas/UUID'
        generationType:
          $ref: '#/components/schemas/GenerationType'
        generationDate:
          type: string
          format: date-time
        author:
          type: string
        details:
          type: string
        batch:
          type: boolean

    # enums
    MessageType:
      type: string
      enum:
        - SOCIAL_ENGINEERING
        - TROLLING
        - GENUINE

    MessageTopic:
      type: string
      enum:
        - WORK
        - SPORT
        - POLITICS
        - SCIENCE
        - TECHNOLOGY
        - ART
        - MUSIC
        - MOVIES
        - GAMES
        - LITERATURE
        - PHILOSOPHY
        - RELIGION
        - HISTORY
        - GEOGRAPHY
        - ECONOMY
        - SOCIETY
        - HEALTH
        - EDUCATION
        - ENVIRONMENT
        - ROMANCE
        - OTHER

    GenerationType:
      type: string
      enum:
        - INSTANT_MESSAGE
        - CONVERSATION

