/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ConversationMessagesPage } from '../model/models';
import { ErrorResponse } from '../model/models';
import { PagedConversationMessageQuery } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ConversationMessageServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Search conversation messages with pagination
     * Search conversation messages with pagination
     * @param pagedConversationMessageQuery 
     */
    searchConversationMessagesPaginate(pagedConversationMessageQuery?: PagedConversationMessageQuery, extraHttpRequestParams?: any): Observable<ConversationMessagesPage>;

}
