/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageTopic } from './message-topic';
import { MessageType } from './message-type';
import { GenerationType } from './generation-type';


export interface ConversationSummary { 
    id?: string;
    generationId?: string;
    generationBusinessId?: string;
    generationType?: GenerationType;
    messageType?: MessageType;
    messageTopic?: MessageTopic;
    maxInteractionNumber?: number;
    minInteractionNumber?: number;
}
export namespace ConversationSummary {
}


