/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageTopic } from './message-topic';
import { MessageType } from './message-type';
import { GenerationType } from './generation-type';


export interface Generation { 
    id?: string;
    generationId?: string;
    creationDate?: string;
    modificationDate?: string;
    generationDate?: string;
    generationType?: GenerationType;
    messageType?: MessageType;
    messageTopic?: MessageTopic;
    userPrompt?: string;
    systemPrompt?: string;
    author?: string;
    details?: string;
    quantity?: number;
    datasetId?: string;
}
export namespace Generation {
}


