/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageTopic } from './message-topic';
import { MessageType } from './message-type';


export interface InstantMessageQuery { 
    messageType?: MessageType;
    messageTopic?: MessageTopic;
    content?: string;
    startDate?: string;
    endDate?: string;
}
export namespace InstantMessageQuery {
}


