/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MessageType = 'SOCIAL_ENGINEERING' | 'TROLLING' | 'GENUINE';

export const MessageType = {
    SocialEngineering: 'SOCIAL_ENGINEERING' as MessageType,
    Trolling: 'TROLLING' as MessageType,
    Genuine: 'GENUINE' as MessageType
};

