/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ConversationSortEnum = 'MESSAGE_TYPE' | 'MESSAGE_TOPIC' | 'MAX_INTERACTION_NUMBER' | 'MIN_INTERACTION_NUMBER' | 'DATE';

export const ConversationSortEnum = {
    MessageType: 'MESSAGE_TYPE' as ConversationSortEnum,
    MessageTopic: 'MESSAGE_TOPIC' as ConversationSortEnum,
    MaxInteractionNumber: 'MAX_INTERACTION_NUMBER' as ConversationSortEnum,
    MinInteractionNumber: 'MIN_INTERACTION_NUMBER' as ConversationSortEnum,
    Date: 'DATE' as ConversationSortEnum
};

