/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GenerationSortEnum = 'GENERATION_TYPE' | 'MESSAGE_TYPE' | 'MESSAGE_TOPIC' | 'USER_PROMPT' | 'SYSTEM_PROMPT' | 'QUANTITY' | 'AUTHOR' | 'DATE';

export const GenerationSortEnum = {
    GenerationType: 'GENERATION_TYPE' as GenerationSortEnum,
    MessageType: 'MESSAGE_TYPE' as GenerationSortEnum,
    MessageTopic: 'MESSAGE_TOPIC' as GenerationSortEnum,
    UserPrompt: 'USER_PROMPT' as GenerationSortEnum,
    SystemPrompt: 'SYSTEM_PROMPT' as GenerationSortEnum,
    Quantity: 'QUANTITY' as GenerationSortEnum,
    Author: 'AUTHOR' as GenerationSortEnum,
    Date: 'DATE' as GenerationSortEnum
};

