/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortDirection } from './sort-direction';
import { ConversationMessageQuery } from './conversation-message-query';
import { QueryPage } from './query-page';
import { ConversationMessageSortEnum } from './conversation-message-sort-enum';


export interface PagedConversationMessageQuery { 
    page: QueryPage;
    query: ConversationMessageQuery;
    sortField?: ConversationMessageSortEnum;
    sortDirection?: SortDirection;
}
export namespace PagedConversationMessageQuery {
}


