/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConversationQuery } from './conversation-query';
import { SortDirection } from './sort-direction';
import { QueryPage } from './query-page';
import { ConversationSortEnum } from './conversation-sort-enum';


export interface PagedConversationQuery { 
    page: QueryPage;
    query: ConversationQuery;
    sortField?: ConversationSortEnum;
    sortDirection?: SortDirection;
}
export namespace PagedConversationQuery {
}


