/**
 * FpGen api
 * API for fake profile dataset generator project
 *
 * The version of the OpenAPI document: 1.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Pagination { 
    /**
     * The current page number
     */
    page: number;
    /**
     * The number of elements of current page
     */
    size: number;
    /**
     * The total number of elements matching the given query
     */
    totalSize: number;
}

